### ISSUE TITLE
Rename "TEG" to "TEA"

### ISSUE THREAD

**Issue by philschatz** [Connexions/cnx-rulesets#173]
The names should be based on the group that wants the work done, not the tool that these books are being imported into. (From discussions in [CTE.Webview1](https://docs.google.com/document/d/1D4Y5NC9QebJxPHuDA8n_APKGeVMWxWJKPdtiV7XUKc8/edit#heading=h.aukol71hqwa5) )

**Comment by helenemccarron** [comment]
Where should this be done? All files or variables are currently using TEA as a prefix.

**Comment by philschatz** [comment]
I created the issue just to make sure it did not get lost. Nothing to see here...
