### ISSUE TITLE
AP Bio Sample => Section Summaries getting collated to EoC

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-rulesets#196]
# Scenario

“Section Summary” sections collated to End of Chapter in the WebView collection, but not in the sample PDF.

Additional note: If these are not supposed to be collated we may need to discuss updating the book mapping spreadsheets with Kerwin.

# Reproducibility Details

* **Impact area**: Content
*  **User**: n/a
*  **URL / Location**: https://tea.cnx.org/contents/-FI3wVe1@1.1:0qjwqv79@1.1/Chapter-Summary
* **How many times were you able to reproduce the issue?** Each section / chapter

*  **Steps to reproduce**:

n/a

* **Images or screenshots Included:** Yes  (_attach below_)
![image](https://cloud.githubusercontent.com/assets/12678235/26212008/c56b148c-3bb9-11e7-9868-18b804da2335.png)
![image](https://cloud.githubusercontent.com/assets/12678235/26212016/caa2f528-3bb9-11e7-871e-dc7d31b3296e.png)

# Environment:

* **Instance**: TEA
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by helenemccarron** [comment]
This is a content issue, the collation instructions are missing classes used in the summary.  Ryan fixed the sample collection for TEA ap bio.
