### ISSUE TITLE
College Biology => Empty box in Link to Learning

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-rulesets#202]
There's a random empty box in the Link to Learning above the section 'The Periodic Table' in Chapter 2.1. 

Webview URL: https://dev00.cnx.org/contents/GFy_h8cu@10.61:vogY0C26@17/21-Atoms-Isotopes-Ions-and-Mol
Text to search: `how to tell one isotope from another`

This may be a content issue, it looks the same on production:
https://cnx.org/contents/GFy_h8cu@10.99:vogY0C26@18/Atoms-Isotopes-Ions-and-Molecu

Webview (dev00) on the left, PDF on the right:
![image](https://cloud.githubusercontent.com/assets/11298165/26317946/e6aed61a-3ede-11e7-8572-0c45dfc5e6ec.png)

**Comment by kerwinso** [comment]
Also found in chapter 5.3:

![image](https://cloud.githubusercontent.com/assets/11298165/26455451/db03b7ec-412f-11e7-9040-297e306db888.png)

**Comment by helenemccarron** [comment]
These are iFrames not being rendered properly in webview. This is an issue on production. 

![2017-05-30_14-20-32](https://cloud.githubusercontent.com/assets/8514591/26600834/317ac7e8-4543-11e7-8c67-4e1cc4808748.png)

**Comment by kerwinso** [comment]
Apparently, users have been reporting these types of issues via the [Biology Errata page](https://openstax.org/errata/?book=Biology) -- see https://openstax.org/errata/2899.

I've alerted Alina (who is not a member of this repo) to this issue. Hopefully it can be addressed with a content fix/update.

Since this issue does not appear to be related to ruleset development, and is already represented in the Errata list, I'm closing it as 'wontfix'.

**Comment by kerwinso** [comment]
Alina filed errata for this bug.
