### ISSUE TITLE
TEG => h3 level titles within sections disappearing.

### ISSUE THREAD

**Issue by Stackblocks** [Connexions/cnx-rulesets#217]
# Scenario
In the gateway h3 element titles set in the body of a section are getting discarded

# Reproducibility Details

* **Impact area**: Content
*  **User**: Alan / Helene
*  **URL / Location**: https://stg.texasgateway.org/resource/12-themes-and-concepts-biology
* **How many times were you able to reproduce the issue?** n/a

*  **Steps to reproduce**:
  1. Load the webpage.
  2. Scroll down to Sensitivity or Response to Stimuli.
  3. Scroll down to the QR code below.
  4. Is there a title that says `Link to Learning`?

* **Images or screenshots Included:** Yes  (_attach below_)
#### Linked Example
![image](https://cloud.githubusercontent.com/assets/12678235/26412961/0c403f9e-4070-11e7-9a58-a0f51511c02e.png)

#### Previous instances
![image](https://cloud.githubusercontent.com/assets/12678235/26412824/9a60de24-406f-11e7-8d46-a8759da168ab.png)
![image](https://cloud.githubusercontent.com/assets/12678235/26412843/ad5b14a4-406f-11e7-9d28-3b60aede5285.png)

# Environment:

* **Instance**: TEA
* **OS**: macOS
* **Browser**: Chrome

# Impact

* **Severity**: High
* **Frequency of occurrence**: Common

**Comment by Stackblocks** [comment]
As an additional note, it looks like the version of MathJax CDN being used in the testing environment is the one that is being sunsetted, so y'all may want to replace that so the math keeps working.

![image](https://cloud.githubusercontent.com/assets/12678235/26415315/b5033378-4077-11e7-87ab-c58044e2fdaa.png)

**Comment by Stackblocks** [comment]
A non-link-to-learning example from the AP Bio Sample.

![image](https://cloud.githubusercontent.com/assets/12678235/26469536/f41ff77e-415f-11e7-929f-82ef474177fa.png)

**Comment by chcase** [comment]
Thanks for those examples.   We found the code that was causing the omission.  It has been fixed and confirmed on staging.  Take a look at this example to confirm: https://stg.texasgateway.org/resource/33-resistance-and-resistivity

We are also looking into updating the mathjax module and will keep you posted on the timing

**Comment by Stackblocks** [comment]
Fix appears propagated through test content. 

![image](https://cloud.githubusercontent.com/assets/12678235/26590731/00a830c8-4521-11e7-8deb-fefd9d3e973c.png)
